# Generated by Django 5.0.6 on 2024-05-29 00:02

import django.core.files.storage
import food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('icon_image', models.ImageField(help_text='Upload a 10px x 10px image icon.', storage=django.core.files.storage.FileSystemStorage(base_url='/media/allergy/thumb/', location='D:\\venv\\foodiefinder\\media\\allergy'), upload_to=food.models.RenameUpload(), verbose_name='Allergy Icon Image')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
