# Generated by Django 5.0.6 on 2024-05-29 16:14

import django.core.files.storage
import food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['title'], 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterField(
            model_name='allergy',
            name='icon_image',
            field=models.ImageField(help_text='Upload a 10px x 10px image icon.', storage=django.core.files.storage.FileSystemStorage(base_url='/media/allergy/', location='D:\\MyFiles\\django\\foodiefinder\\media\\allergy'), upload_to=food.models.RenameUpload(), verbose_name='Allergy Icon Image'),
        ),
    ]
